#define _ZERO_WITH_COMMA_1 0,
#define _second_arg(__ignored, val, ...) val
#define _is_enabled(x)                __is_enabled(x)
#define __is_enabled(val)             ___is_enabled(_ZERO_WITH_COMMA_##val)
#define ___is_enabled(junk_or_comma)  _second_arg(junk_or_comma 1, 0)
#define IS_ENABLED(config)            _is_enabled(config)
#define BL616CL 1
#undef CONFIG_ANTI_ROLLBACK
#define CONFIG_APP_ANTI_ROLLBACK_VER 0
#define CONFIG_ARDUINO_RUNTIME_PROFILE "bridge"
#define CONFIG_BACKTRACE 1
#undef CONFIG_BFLB_LOG
#define CONFIG_BFLB_MTD 1
#undef CONFIG_BLE_USE_MAC2
#define CONFIG_BLUETOOTH 1
#define CONFIG_BSP_USB 1
#define CONFIG_BTBLECONTROLLER_LIB "m2s1"
#define CONFIG_BT_SETTINGS 1
#undef CONFIG_BT_STACK_CLI
#define CONFIG_CHERRYUSB 1
#define CONFIG_CHERRYUSB_DEVICE 1
#define CONFIG_CHERRYUSB_DEVICE_CDC 1
#define CONFIG_CHERRYUSB_DEVICE_CDC_ACM 1
#define CONFIG_CHERRYUSB_DEVICE_HID 1
#define CONFIG_COMX "COM5"
#define CONFIG_CONSOLE_UART_BAUDRATE 2000000
#define CONFIG_COREDUMP 1
#define CONFIG_DEBUG 1
#define CONFIG_DHCPD 1
#define CONFIG_FHOST 1
#define CONFIG_FREERTOS 1
#undef CONFIG_GCC_COMPILE_LTO
#define CONFIG_GCC_OPTIMISE_LEVEL "-Os"
#define CONFIG_LITTLEFS 1
#define CONFIG_LITTLEFS_KV_EASYFLASH 1
#define CONFIG_LOG_LEVEL 3
#define CONFIG_LWIP 1
#define CONFIG_MACSW_SELECT "default"
#define CONFIG_MBEDTLS 1
#define CONFIG_MBEDTLS_AES_USE_HW 1
#define CONFIG_MBEDTLS_BIGNUM_USE_HW 1
#define CONFIG_MBEDTLS_ECC_USE_HW 1
#define CONFIG_MBEDTLS_SHA1_USE_HW 1
#define CONFIG_MBEDTLS_SHA256_USE_HW 1
#define CONFIG_MBEDTLS_SHA512_USE_HW 1
#undef CONFIG_MULTIMEDIA_VIDEO
#define CONFIG_PARTITION 1
#undef CONFIG_PEC_V2
#define CONFIG_PING 1
#define CONFIG_POSIX 1
#define CONFIG_RF 1
#define CONFIG_ROMAPI 1
#undef CONFIG_SHELL
#define CONFIG_TLSF 1
#define CONFIG_VSNPRINTF_FLOAT 1
#define CONFIG_VSNPRINTF_FLOAT_EX 1
#define CONFIG_VSNPRINTF_LONG_LONG 1
#define CONFIG_WIFI6 1
#undef CONFIG_XTAL_POWER_TYPE_ACTIVE
