#define _ZERO_WITH_COMMA_1 0,
#define _second_arg(__ignored, val, ...) val
#define _is_enabled(x)                __is_enabled(x)
#define __is_enabled(val)             ___is_enabled(_ZERO_WITH_COMMA_##val)
#define ___is_enabled(junk_or_comma)  _second_arg(junk_or_comma 1, 0)
#define IS_ENABLED(config)            _is_enabled(config)
#define CONFIG_ADV_EXTENSION 1
#define CONFIG_AES_IV ""
#define CONFIG_AES_KEY ""
#undef CONFIG_ANTI_ROLLBACK
#undef CONFIG_APP_BUILD_TYPE_DIRECT_BOOT_APP
#define CONFIG_APP_BUILD_TYPE_STD_APP 1
#undef CONFIG_ATMODULE_NANO
#undef CONFIG_ATMODULE_NETHUB_WIFICHANNELAUTO
#undef CONFIG_ATMODULE_WIFI
#undef CONFIG_ATMODULE_WIFI_AP
#undef CONFIG_ATMODULE_WIFI_STA
#undef CONFIG_AUDIO_MIC_PDM_MODE
#undef CONFIG_AUTO_PTS
#undef CONFIG_BACKTRACE
#undef CONFIG_BFLB_BLESYNC
#undef CONFIG_BFLB_BLETP_SVC
#undef CONFIG_BFLB_BLOCK_POOL_DEBUG
#undef CONFIG_BFLB_LOG
#undef CONFIG_BFLB_MTD
#define CONFIG_BIS 1
#undef CONFIG_BL702_USE_ROM_DRIVER
#define CONFIG_BLE 1
#define CONFIG_BLECONTROLLER_LIB ""
#define CONFIG_BLE_ACT_MAX 7
#undef CONFIG_BLE_AT_CMD
#undef CONFIG_BLE_BEACON_ONLY
#undef CONFIG_BLE_HOST_DISABLE
#define CONFIG_BLE_IF ""
#undef CONFIG_BLE_MULTI_ADV
#undef CONFIG_BLE_PDS
#undef CONFIG_BLE_RECONNECT_TEST
#define CONFIG_BLE_STACK_DBG_PRINT 1
#undef CONFIG_BLE_TP_SERVER
#undef CONFIG_BLE_TP_TEST
#define CONFIG_BLE_TX_BUFF_DATA 2
#undef CONFIG_BLE_USE_MAC2
#define CONFIG_BLE_USING_DYNAMIC_RAM 0
#define CONFIG_BLUETOOTH 1
#define CONFIG_BL_WPA_SUPPLICANT 1
#define BOARD "bl616cldk"
#define CONFIG_BOARD_BOOT2FILE "/home/virusv/bouffalolab/bouffalo_sdk_full/bouffalo_sdk/bsp/board/bl616cldk/config/boot2_bl616cl_isp_release_v8.2.1.bin"
#define CONFIG_BOARD_DTSFILE "/home/virusv/bouffalolab/bouffalo_sdk_full/bouffalo_sdk/bsp/board/bl616cldk/config/bl_factory_params_IoTKitA_auto.dts"
#undef CONFIG_BOARD_FLASH_LOW_SPEED
#define CONFIG_BOARD_PTFILE "/home/virusv/bouffalolab/bouffalo_sdk_full/bouffalo_sdk/bsp/board/bl616cldk/config/partition_cfg_4M.toml"
#undef CONFIG_BOOT2
#define CONFIG_BOOT2_ANTI_ROLLBACK_VER 0
#define CONFIG_BOOT2_VER ""
#define BOUFFALO_SDK 1
#undef CONFIG_BSP_ADC_KEY
#undef CONFIG_BSP_AUDIO_CODEC
#undef CONFIG_BSP_AUDIO_PLAYER
#undef CONFIG_BSP_CONSOLE_USB_CDC
#undef CONFIG_BSP_CSI
#define CONFIG_BSP_EMAC_MDIO_DEFAULT_PORT 0
#define CONFIG_BSP_EMAC_RMII_DEFAULT_PORT 0
#undef CONFIG_BSP_ETH_PHY
#undef CONFIG_BSP_IMAGE_SENSOR
#undef CONFIG_BSP_LCD
#undef CONFIG_BSP_LWIP_NETIF_EMAC
#undef CONFIG_BSP_MR
#undef CONFIG_BSP_SDH_OSAL_POLLING_MODE
#undef CONFIG_BSP_SDH_SD
#undef CONFIG_BSP_SDH_SDCARD
#undef CONFIG_BSP_SDH_SDIO
#undef CONFIG_BSP_SPI_SDCARD
#undef CONFIG_BSP_TOUCH
#undef CONFIG_BSP_USB
#define CONFIG_BTBLECONTROLLER_LIB "uarthci"
#define CONFIG_BTBLE_IF ""
#undef CONFIG_BT_A2DP
#define CONFIG_BT_ALLROLES 1
#define CONFIG_BT_ATT_PREPARE_COUNT 0
#undef CONFIG_BT_AVRCP
#undef CONFIG_BT_BAS_SERVER
#undef CONFIG_BT_BREDR
#define CONFIG_BT_BROADCASTER 1
#define CONFIG_BT_CENTRAL 1
#define CONFIG_BT_CONN 1
#undef CONFIG_BT_CONTROLLER_DISABLE
#define CONFIG_BT_DATA_LEN_UPDATE 1
#undef CONFIG_BT_DEBUG_MONITOR
#define CONFIG_BT_DIRECT_TEST_MODE 1
#undef CONFIG_BT_DIS_SERVER
#undef CONFIG_BT_FIXED_PASSKEY
#undef CONFIG_BT_GAP_PERIPHERAL_PREF_PARAMS
#define CONFIG_BT_GATT_CLIENT 1
#undef CONFIG_BT_GEN_RANDOM_BY_SW
#define CONFIG_BT_HCI_TEST_MODE 1
#undef CONFIG_BT_HOST_HCI
#undef CONFIG_BT_HOST_HCI_TL
#undef CONFIG_BT_IAS_SERVER
#define CONFIG_BT_IF ""
#define CONFIG_BT_L2CAP_TX_MTU 247
#undef CONFIG_BT_MESH
#undef CONFIG_BT_NEARBY
#undef CONFIG_BT_OAD_CLIENT
#undef CONFIG_BT_OAD_SERVER
#define CONFIG_BT_OBSERVER 1
#undef CONFIG_BT_PATH
#define CONFIG_BT_PERIPHERAL 1
#undef CONFIG_BT_REMOTE_CONTROL
#undef CONFIG_BT_RESET
#define CONFIG_BT_RX_BUF_LEN 255
#define CONFIG_BT_RX_STACK_SIZE 2048
#undef CONFIG_BT_SCPS_SERVER
#undef CONFIG_BT_SETTINGS
#undef CONFIG_BT_SMP_ENFORCE_MITM
#undef CONFIG_BT_SPP_SERVER
#define CONFIG_BT_STACK_CLI 1
#undef CONFIG_BT_STACK_PTS
#undef CONFIG_BT_TL
#undef CONFIG_BT_TP_CLI
#define CONFIG_BT_WORK_QUEUE_STACK_SIZE 2048
#undef CONFIG_BUILD_ROM_CODE
#define CONFIG_CHERRYUSB 1
#define CONFIG_CHERRYUSB_DEVICE 1
#undef CONFIG_CHERRYUSB_DEVICE_AUDIO
#undef CONFIG_CHERRYUSB_DEVICE_CDC
#define CONFIG_CHERRYUSB_DEVICE_CDC_ACM 1
#undef CONFIG_CHERRYUSB_DEVICE_CDC_ECM
#undef CONFIG_CHERRYUSB_DEVICE_CDC_RNDIS
#undef CONFIG_CHERRYUSB_DEVICE_DFU
#undef CONFIG_CHERRYUSB_DEVICE_GAMEPAD
#define CONFIG_CHERRYUSB_DEVICE_HID 1
#undef CONFIG_CHERRYUSB_DEVICE_MSC
#undef CONFIG_CHERRYUSB_DEVICE_VIDEO
#undef CONFIG_CHERRYUSB_HOST
#define CONFIG_CHERRYUSB_OSAL "freertos"
#define CHIP "bl616cl"
#define CONFIG_CIS 1
#define CONFIG_CLK_ACC 1
#undef CONFIG_COEX
#define CONFIG_COEX_WIFI_MODE 0
#define CONFIG_COMX "COM5"
#define CONFIG_CONSOLE_UART_BAUDRATE 2000000
#undef CONFIG_CONSOLE_WO
#define CONFIG_CON_ACL 0
#undef CONFIG_COREDUMP
#define CPU_ID ""
#define CPU_MODEL ""
#define CONFIG_CSB 1
#define CONFIG_CTE 1
#undef CONFIG_CUSTOM_LINKSCRIPT
#undef CONFIG_DBG_RUN_ON_FPGA
#define CONFIG_DEBUG 1
#define CONFIG_DHCPD 1
#define CONFIG_DISABLE_BT_HOST_PRIVACY 1
#undef CONFIG_DISABLE_BT_SMP
#undef CONFIG_DUALCORE_DISABLE
#define CONFIG_DUALCORE_NP_IMAGE ""
#undef CONFIG_DUAL_ETH
#undef CONFIG_DVP_RASTER
#undef CONFIG_DYNAMIC_GATTS
#undef CONFIG_EASYFLASH4
#define CONFIG_EMAC0_MDIO_ID 0
#define CONFIG_EMAC0_RMII_ID 0
#define CONFIG_EMAC_DEV_COUNT 1
#undef CONFIG_EM_16K
#undef CONFIG_EM_HEAP_DISABLE
#define CONFIG_EM_SIZE 64
#undef CONFIG_ENABLE_IMG_HASH
#undef CONFIG_ERR_NOT_DUMP_ALL_REGS
#undef CONFIG_EXPORT_COMPILE_COMMANDS
#undef CONFIG_FATFS
#undef CONFIG_FHOST
#undef CONFIG_FLASH_4BYTE_ADDR_MODE_ENABLE
#undef CONFIG_FLASH_AUTO_2LINE_FALLBACK
#define CONFIG_FLASH_XIP_LENGTH 0x400000
#undef CONFIG_FOTA
#define CONFIG_FREERTOS 1
#undef CONFIG_FREERTOS_DISABLE
#define CONFIG_FW_POST_PROC_CUSTOM ""
#undef CONFIG_GCC_COMPILE_LTO
#undef CONFIG_GCC_LINK_NO_RELAX
#define CONFIG_GCC_OPTIMISE_LEVEL "-Os"
#undef CONFIG_HEAP_ALWAYS_ON_KMEM
#undef CONFIG_HIGH_ISR_STACK
#undef CONFIG_HOGP_SERVER
#undef CONFIG_HOSTROUTER
#undef CONFIG_HTTP
#undef CONFIG_HTTPD
#undef CONFIG_HTTPS_OTA_USE_CA_CERT
#undef CONFIG_HTTPS_OTA_USE_CLIENT_CERT
#undef CONFIG_HW_SEC_ENG_DISABLE
#undef CONFIG_INCLUDE_PHYRF_HEADER
#undef CONFIG_IPC
#undef CONFIG_IPERF
#undef CONFIG_IPV6
#define CONFIG_LE_PING 1
#define CONFIG_LE_PWR_CTRL 1
#undef CONFIG_LHAL_BOOTROM_ROMDRIVER
#undef CONFIG_LIBPEER
#undef CONFIG_LITTLEFS
#undef CONFIG_LMAC154
#define CONFIG_LONG_RANG 1
#undef CONFIG_LPAPP
#undef CONFIG_LPFW_CUSTOM_RX
#undef CONFIG_LP_HCIUART
#undef CONFIG_LUA_LHAL
#undef CONFIG_LVGL8
#undef CONFIG_LVGL9
#define CONFIG_LWIP 1
#undef CONFIG_LWIP_ALTCP
#undef CONFIG_LWIP_LP
#undef CONFIG_MACSW_LOG_NO_PRINT
#define CONFIG_MACSW_SELECT "default"
#define CONFIG_MBEDTLS 1
#define CONFIG_MBEDTLS_AES_FEWER_TABLES 1
#define CONFIG_MBEDTLS_AES_ROM_TABLES 1
#define CONFIG_MBEDTLS_AES_USE_HW 1
#define CONFIG_MBEDTLS_BIGNUM_USE_HW 1
#define CONFIG_MBEDTLS_CFG_FILE "config-tls-generic.h"
#define CONFIG_MBEDTLS_CIPHER 1
#define CONFIG_MBEDTLS_CIPHER_AES_ENABLED 1
#undef CONFIG_MBEDTLS_CIPHER_ALL_ENABLED
#undef CONFIG_MBEDTLS_CIPHER_CAMELLIA_ENABLED
#undef CONFIG_MBEDTLS_CIPHER_CCM_ENABLED
#undef CONFIG_MBEDTLS_CIPHER_CHACHA20_ENABLED
#define CONFIG_MBEDTLS_CIPHER_DES_ENABLED 1
#define CONFIG_MBEDTLS_CIPHER_GCM_ENABLED 1
#define CONFIG_MBEDTLS_CIPHER_MODE_CBC_ENABLED 1
#undef CONFIG_MBEDTLS_CIPHER_MODE_CFB_ENABLED
#define CONFIG_MBEDTLS_CIPHER_MODE_CTR_ENABLED 1
#undef CONFIG_MBEDTLS_CIPHER_MODE_OFB_ENABLED
#undef CONFIG_MBEDTLS_CIPHER_MODE_XTS_ENABLED
#undef CONFIG_MBEDTLS_CMAC
#define CONFIG_MBEDTLS_CTR_DRBG_ENABLED 1
#undef CONFIG_MBEDTLS_DEBUG
#define CONFIG_MBEDTLS_DHM_C 1
#undef CONFIG_MBEDTLS_DTLS
#define CONFIG_MBEDTLS_ECC_USE_HW 1
#define CONFIG_MBEDTLS_ECDH_C 1
#define CONFIG_MBEDTLS_ECDSA_C 1
#undef CONFIG_MBEDTLS_ECDSA_DETERMINISTIC
#undef CONFIG_MBEDTLS_ECJPAKE_C
#undef CONFIG_MBEDTLS_ECP_ALL_ENABLED
#define CONFIG_MBEDTLS_ECP_C 1
#undef CONFIG_MBEDTLS_ECP_DP_BP256R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_BP384R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_BP512R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_CURVE25519_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_CURVE448_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP192K1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP192R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP224K1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP224R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP256K1_ENABLED
#define CONFIG_MBEDTLS_ECP_DP_SECP256R1_ENABLED 1
#undef CONFIG_MBEDTLS_ECP_DP_SECP384R1_ENABLED
#undef CONFIG_MBEDTLS_ECP_DP_SECP521R1_ENABLED
#define CONFIG_MBEDTLS_ECP_NIST_OPTIM 1
#define CONFIG_MBEDTLS_ENTROPY_C 1
#define CONFIG_MBEDTLS_ENTROPY_POLL 1
#define CONFIG_MBEDTLS_GENPRIME_ENABLED 1
#undef CONFIG_MBEDTLS_HASH_ALL_ENABLED
#define CONFIG_MBEDTLS_HAVE_ASM 1
#undef CONFIG_MBEDTLS_HAVE_TIME
#undef CONFIG_MBEDTLS_HKDF_C
#undef CONFIG_MBEDTLS_HMAC_DRBG_ENABLED
#undef CONFIG_MBEDTLS_KEY_EXCHANGE_ALL_ENABLED
#undef CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_PSK_ENABLED
#define CONFIG_MBEDTLS_KEY_EXCHANGE_DHE_RSA_ENABLED 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_ECDSA_ENABLED 1
#undef CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_PSK_ENABLED
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDHE_RSA_ENABLED 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_ECDSA_ENABLED 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_ECDH_RSA_ENABLED 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_PSK_ENABLED 1
#define CONFIG_MBEDTLS_KEY_EXCHANGE_RSA_ENABLED 1
#undef CONFIG_MBEDTLS_KEY_EXCHANGE_RSA_PSK_ENABLED
#define CONFIG_MBEDTLS_MD 1
#define CONFIG_MBEDTLS_MD5 1
#undef CONFIG_MBEDTLS_NIST_KW_C
#define CONFIG_MBEDTLS_PEM_CERTIFICATE_FORMAT 1
#define CONFIG_MBEDTLS_PKCS5_C 1
#define CONFIG_MBEDTLS_PK_WRITE_C 1
#undef CONFIG_MBEDTLS_PLATFORM_NO_SYSTEM_ALLOCATOR
#undef CONFIG_MBEDTLS_POLY1305
#undef CONFIG_MBEDTLS_PSA_CRYPTO_C
#define CONFIG_MBEDTLS_PSK_MAX_LEN 32
#undef CONFIG_MBEDTLS_SELF_TEST
#define CONFIG_MBEDTLS_SERVER_NAME_INDICATION 1
#define CONFIG_MBEDTLS_SHA1 1
#define CONFIG_MBEDTLS_SHA1_USE_HW 1
#define CONFIG_MBEDTLS_SHA224 1
#define CONFIG_MBEDTLS_SHA256 1
#define CONFIG_MBEDTLS_SHA256_SMALLER 1
#define CONFIG_MBEDTLS_SHA256_USE_HW 1
#undef CONFIG_MBEDTLS_SHA3
#define CONFIG_MBEDTLS_SHA384 1
#define CONFIG_MBEDTLS_SHA512 1
#define CONFIG_MBEDTLS_SHA512_USE_HW 1
#define CONFIG_MBEDTLS_SOME_AEAD_CIPHER_ENABLED 1
#define CONFIG_MBEDTLS_SOME_CIPHER_ENABLED 1
#define CONFIG_MBEDTLS_SSL_ALPN 1
#undef CONFIG_MBEDTLS_SSL_CACHE_C
#undef CONFIG_MBEDTLS_SSL_EXTENDED_MASTER_SECRET
#undef CONFIG_MBEDTLS_SSL_KEEP_PEER_CERTIFICATE
#define CONFIG_MBEDTLS_SSL_MAX_CONTENT_LEN 16384
#undef CONFIG_MBEDTLS_SSL_VARIABLE_BUFFER_LENGTH
#define CONFIG_MBEDTLS_TLS_VERSION_1_2 1
#undef CONFIG_MBEDTLS_TLS_VERSION_1_3
#undef CONFIG_MBEDTLS_USER_CONFIG_ENABLE
#undef CONFIG_MBEDTLS_USE_PSA_CRYPTO
#undef CONFIG_MBEDTLS_V2
#undef CONFIG_MBEDTLS_X509_CRL_PARSE_C
#undef CONFIG_MBEDTLS_X509_CRT_WRITE_C
#undef CONFIG_MBEDTLS_X509_CSR_PARSE_C
#undef CONFIG_MBEDTLS_X509_CSR_WRITE_C
#undef CONFIG_MBEDTLS_X509_TRUSTED_CERT_CALLBACK
#undef CONFIG_MDNS
#undef CONFIG_MEMTESTER
#undef CONFIG_MEM_HEAP5_EN
#define CONFIG_MEM_TLSF_EN 1
#undef CONFIG_MFG_SDIO
#undef CONFIG_MFG_USB
#undef CONFIG_MM_ENABLE_MIN_FREE_TRACKING
#undef CONFIG_MM_ENABLE_TRACKING
#undef CONFIG_MM_SUSPEND_ALL_LOCKER
#undef CONFIG_MQTT
#undef CONFIG_MQUICKJS
#undef CONFIG_MULTIMEDIA
#undef CONFIG_MULTIMEDIA_VIDEO
#undef CONFIG_NETBUS
#undef CONFIG_NETHUB
#undef CONFIG_NEWLIB_FATFS
#undef CONFIG_NEWLIB_LITTLEFS
#undef CONFIG_NIMBLE
#undef CONFIG_NIMBLE_STACK_CLI
#undef CONFIG_NO_SHORT_ENUMS
#undef CONFIG_NUTTX
#undef CONFIG_OPENAMP_PROXY
#undef CONFIG_OPENAMP_VIRTIO_DEVICE_SUPPORT
#undef CONFIG_OPENAMP_VIRTIO_DRIVER_SUPPORT
#undef CONFIG_OTA_HEADER_USE_SDK_VERSION
#define CONFIG_OTA_VERSION_PREFIX ""
#define CONFIG_OT_SERIAL ""
#define CONFIG_OVERRIDE_BOOT2FILE ""
#define CONFIG_OVERRIDE_DTSFILE ""
#define CONFIG_OVERRIDE_MFGFILE ""
#define CONFIG_OVERRIDE_PTFILE ""
#undef CONFIG_PARTITION
#define CONFIG_PCA 1
#undef CONFIG_PEC_V2
#undef CONFIG_PHY_CLI
#undef CONFIG_PHY_LPFW
#define CONFIG_PHY_UPDATE 1
#define CONFIG_PING 1
#undef CONFIG_PM
#undef CONFIG_PMP_NOT_INIT
#undef CONFIG_PMP_NO_INIT
#undef CONFIG_PM_PDS_FLASH_POWER_OFF
#undef CONFIG_PM_PDS_PLL_POWER_OFF
#undef CONFIG_PM_PDS_RF_POWER_OFF
#define CONFIG_POSIX 1
#define CONFIG_POST_BUILDS ""
#undef CONFIG_POST_BUILDS_CONCAT_WITH_LP_FW
#undef CONFIG_POST_BUILDS_GENERATE_LITTLEFS
#undef CONFIG_POST_BUILDS_GENERATE_ROMFS
#define CONFIG_POST_BUILDS_LITTLEFS_SIZE 0x0
#define CONFIG_PRIVATE_KEY ""
#define CONFIG_PROJECT_SDK_VERSION "1.1.1"
#undef CONFIG_PSRAM
#undef CONFIG_PSRAM_COPY_CODE
#define CONFIG_PSRAM_LENGTH 0x400000
#undef CONFIG_PS_EXTEND
#undef CONFIG_PTS_GAP_SLAVER_CONFIG_INDICATE_CHARC
#undef CONFIG_PTS_TEST_CASE_INSUFFICIENT_KEY
#define CONFIG_PUBLIC_KEY ""
#undef CONFIG_PWRMGMT
#define CONFIG_RF 1
#undef CONFIG_RFPARAM_TLV_FIXED_ADDRESS
#undef CONFIG_RFPHY_CLI
#define CONFIG_RF_EXTRC 1
#define CONFIG_ROMAPI 1
#undef CONFIG_ROMFS
#define CONFIG_RSWITCH 1
#undef CONFIG_RTSP
#undef CONFIG_SCANF_FLOAT
#define CONFIG_SCO_ESCO 1
#undef CONFIG_SDIO3_SOFT_RST_INT_USER
#undef CONFIG_SDIO_LPAPP
#define CONFIG_SHELL 1
#define CONFIG_SHELL_AUTOLIST_FILE ""
#define CONFIG_SHELL_CMD_SIZE 128
#define CONFIG_SHELL_THREAD_STACK_SIZE 4096
#undef CONFIG_SIMPLE_MASTER
#undef CONFIG_SKIP_COMBINE
#undef CONFIG_SMARTAUDIO
#define CONFIG_SNIFF 1
#undef CONFIG_SOLN_UTILS
#undef CONFIG_SPI_3PIN_MODE_ENABLE
#undef CONFIG_SRTP
#undef CONFIG_STACK_SWITCH_CALL_SSCANF
#define CONFIG_STA_MAX 5
#undef CONFIG_STDATOMIC
#undef CONFIG_STD_BOOTROM_ROMDRIVER
#undef CONFIG_STRICT
#undef CONFIG_SUBG
#undef CONFIG_TENSORFLOWLITE
#define CONFIG_TEST_MODE 1
#define CONFIG_THIRDCORE_LP_IMAGE ""
#undef CONFIG_THREAD
#undef CONFIG_THREAD_TPERF
#undef CONFIG_TICKLESS_WIFI_BLE
#define CONFIG_TIMEZONE 8
#undef CONFIG_TINYMAIX
#undef CONFIG_TJPGDEC
#define CONFIG_TLSF 1
#undef CONFIG_UNSINGLE_MAC_ADDR
#undef CONFIG_USB_DISABLED
#undef CONFIG_USE_LPAPP
#undef CONFIG_USE_XTAL32K
#define CONFIG_VIRT_DEV_MAX 2
#define CONFIG_VSCODE_PARSE_EN 1
#define CONFIG_VSNPRINTF_FLOAT 1
#define CONFIG_VSNPRINTF_FLOAT_EX 1
#define CONFIG_VSNPRINTF_LONG_LONG 1
#undef CONFIG_VSNPRINTF_NANO
#undef CONFIG_WFA
#undef CONFIG_WIFI4
#define CONFIG_WIFI6 1
#undef CONFIG_WIFI_ENABLE
#undef CONFIG_WIFI_ETH_BRIDGE
#undef CONFIG_WIFI_IPERF
#undef CONFIG_WIFI_MAT
#undef CONFIG_WIFI_MAT_FULL_COPY
#undef CONFIG_WIFI_TG
#define CONFIG_WL80211 1
#undef CONFIG_WL80211_P2P
#define CONFIG_WL80211_WRAM_MEM_SIZE_LIMIT 0x8000
#undef CONFIG_WLAN
#define CONFIG_WLAN_IF ""
#define CONFIG_WLAN_MFG ""
#define CONFIG_WLAN_PROJ_NAME ""
#define CONFIG_WRAM_LENGTH 0x28000
#undef CONFIG_X509_CERTIFICATE_BUNDLE
#undef CONFIG_XTAL_POWER_TYPE_ACTIVE
#undef CONFIG_XZ
#undef CONFIG_ZIGBEE
#undef CONFIG_ZIGBEE_PROV
#define BL616CL 1

#undef CONFIG_BLE_HOST_DISABLE
#define CONFIG_BLE_HOST_DISABLE 1
#undef CONFIG_EM_SIZE
#define CONFIG_EM_SIZE 32
#undef CONFIG_BT_ALLROLES
#define CONFIG_BT_ALLROLES 1
#undef CONFIG_DISABLE_BLE_CONTROLLER_TEST_MODE
#undef CONFIG_BT_CONN
#define CONFIG_BT_CONN 2
#undef CONFIG_BLE_TX_BUFF_DATA
#define CONFIG_BLE_TX_BUFF_DATA 4
#undef CONFIG_BLE_ACT_MAX
#define CONFIG_BLE_ACT_MAX 7
#undef CONFIG_BIS
#define CONFIG_BIS 1
#undef CONFIG_CTE
#undef CONFIG_CIS
#define CONFIG_CIS 1
