#ifndef _BOUFFALO_SDK_H_
#define _BOUFFALO_SDK_H_

#ifdef __cplusplus
extern "C" {
#endif

#include "bsp/board/bl616dk/board.h"
#include "bsp/board/bl616dk/board_rf.h"
#include "bsp/board/bl616dk/fw_header.h"

#include "drivers/rfparam/Inc/rfparam_rftlv.h"
#include "drivers/rfparam/Inc/rfparam_adapter.h"

#include "drivers/lhal/include/compiler/compiler_ld.h"
#include "drivers/lhal/include/compiler/compiler_gcc.h"

#include "drivers/lhal/include/arch/risc-v/riscv_arch.h"
#include "drivers/lhal/include/arch/risc-v/csr.h"
#include "drivers/lhal/include/arch/risc-v/e24/clic.h"
#include "drivers/lhal/include/arch/risc-v/t-head/Core/Include/csi_rv32_gcc.h"
// #include "drivers/lhal/include/arch/risc-v/t-head/Core/Include/csi_rv64_gcc.h"
#include "drivers/lhal/include/arch/risc-v/t-head/Core/Include/core_rv32.h"
// #include "drivers/lhal/include/arch/risc-v/t-head/Core/Include/core_rv64.h"
#include "drivers/lhal/include/arch/risc-v/t-head/Core/Include/csi_core.h"

#include "drivers/lhal/include/arch/risc-v/t-head/rv_hpm.h"
#include "drivers/lhal/include/arch/risc-v/t-head/rv_syscall.h"
#include "drivers/lhal/include/arch/risc-v/t-head/rv_hart.h"
// #include "drivers/lhal/include/arch/risc-v/t-head/rv_Sv39.h"
#include "drivers/lhal/include/arch/risc-v/t-head/rv_pmp.h"
#include "drivers/lhal/include/arch/risc-v/t-head/csi_dsp/include/csi_math.h"
#include "drivers/lhal/include/arch/risc-v/t-head/csi_dsp/include/csi_const_structs.h"
#include "drivers/lhal/include/arch/risc-v/t-head/csi_dsp/include/csi_instance.h"
#include "drivers/lhal/include/arch/risc-v/t-head/csi_dsp/include/csi_common_tables.h"


#include "drivers/soc/bl616/std/include/hardware/ef_ctrl_reg.h"
#include "drivers/soc/bl616/std/include/hardware/glb_reg.h"
#include "drivers/soc/bl616/std/include/hardware/tzc_sec_reg.h"
#include "drivers/soc/bl616/std/include/hardware/mm_glb_reg.h"
#include "drivers/soc/bl616/std/include/hardware/tzc_nsec_reg.h"
#include "drivers/soc/bl616/std/include/hardware/sf_ctrl_reg.h"
#include "drivers/soc/bl616/std/include/hardware/ef_data_reg.h"
#include "drivers/soc/bl616/std/include/hardware/pds_reg.h"
#include "drivers/soc/bl616/std/include/hardware/hbn_reg.h"
#include "drivers/soc/bl616/std/include/hardware/mm_misc_reg.h"
#include "drivers/soc/bl616/std/include/hardware/cci_reg.h"
#include "drivers/soc/bl616/std/include/hardware/sdh_reg.h"
#include "drivers/soc/bl616/std/include/hardware/psram_reg.h"
#include "drivers/soc/bl616/std/include/hardware/bl616.h"
#include "drivers/soc/bl616/std/include/hardware/mcu_misc_reg.h"
#include "drivers/soc/bl616/std/include/hardware/aon_reg.h"
#include "drivers/soc/bl616/std/startup/irq_ctx.h"
#include "drivers/soc/bl616/std/include/bl616_glb.h"
#include "drivers/soc/bl616/std/include/bl616_romdriver_e907.h"
#include "drivers/soc/bl616/std/include/bl616_ef_ctrl.h"
#include "drivers/soc/bl616/std/include/bl616_mfg_efuse.h"
#include "drivers/soc/bl616/std/include/bl616_ef_cfg.h"
#include "drivers/soc/bl616/std/include/bl616_mfg_flash.h"
#include "drivers/soc/bl616/std/include/bl616_tzc_sec.h"
#include "drivers/soc/bl616/std/include/bl616_gpio.h"
#include "drivers/soc/bl616/std/include/bl616_hbn.h"
#include "drivers/soc/bl616/std/include/bl616_l1c.h"
#include "drivers/soc/bl616/std/include/bl616_aon.h"
#include "drivers/soc/bl616/std/include/bl616_sdh.h"
#include "drivers/soc/bl616/std/include/bl616_romapi_patch.h"
#include "drivers/soc/bl616/std/include/bl616_common.h"
#include "drivers/soc/bl616/std/include/bl616_mfg_media.h"
#include "drivers/soc/bl616/std/include/bl616_pds.h"
#include "drivers/soc/bl616/std/include/bl616_sdu.h"
#include "drivers/soc/bl616/std/include/bl616_glb_gpio.h"
#include "drivers/soc/bl616/std/include/bl616_clock.h"
#include "drivers/soc/bl616/std/include/bl616_psram.h"
#include "drivers/soc/bl616/std/include/bl616_pm.h"

#include "drivers/lhal/include/hardware/ef_ctrl_reg.h"
#include "drivers/lhal/include/hardware/dma_reg.h"
#include "drivers/lhal/include/hardware/cks_reg.h"
#include "drivers/lhal/include/hardware/kys_reg.h"
#include "drivers/lhal/include/hardware/adc_reg.h"
#include "drivers/lhal/include/hardware/emac_reg.h"
#include "drivers/lhal/include/hardware/rtc_reg.h"
#include "drivers/lhal/include/hardware/i2c_reg.h"
#include "drivers/lhal/include/hardware/csi_reg.h"
#include "drivers/lhal/include/hardware/audac_reg.h"
#include "drivers/lhal/include/hardware/usb_v1_reg.h"
#include "drivers/lhal/include/hardware/platform_dma_reg.h"
#include "drivers/lhal/include/hardware/dac_reg.h"
#include "drivers/lhal/include/hardware/dtsrc_reg.h"
#include "drivers/lhal/include/hardware/spi_reg.h"
#include "drivers/lhal/include/hardware/mjpeg_reg.h"
#include "drivers/lhal/include/hardware/i2s_reg.h"
#include "drivers/lhal/include/hardware/sf_ctrl_reg.h"
#include "drivers/lhal/include/hardware/timer_reg.h"
#include "drivers/lhal/include/hardware/auadc_reg.h"
#include "drivers/lhal/include/hardware/pwm_v1_reg.h"
#include "drivers/lhal/include/hardware/usb_v2_reg.h"
#include "drivers/lhal/include/hardware/pwm_v2_reg.h"
#include "drivers/lhal/include/hardware/gpio_reg.h"
#include "drivers/lhal/include/hardware/cam_front_reg.h"
#include "drivers/lhal/include/hardware/sdio2_reg.h"
#include "drivers/lhal/include/hardware/uart_reg.h"
#include "drivers/lhal/include/hardware/ir_reg.h"
#include "drivers/lhal/include/hardware/acomp_reg.h"
#include "drivers/lhal/include/hardware/cam_reg.h"
#include "drivers/lhal/include/hardware/dbi_reg.h"
#include "drivers/lhal/include/hardware/sec_eng_reg.h"
#include "drivers/lhal/config/bl616/bl616_memorymap.h"
#include "drivers/lhal/config/bl616/bl616_irq.h"


#include "drivers/lhal/include/bflb_acomp.h"
#include "drivers/lhal/include/bflb_sec_sha.h"
#include "drivers/lhal/include/bflb_mjpeg.h"
#include "drivers/lhal/include/bflb_auadc.h"
#include "drivers/lhal/include/bflb_core.h"
#include "drivers/lhal/include/bflb_spi.h"
#include "drivers/lhal/include/bflb_dbi.h"
#include "drivers/lhal/include/bflb_audac.h"
#include "drivers/lhal/include/bflb_sec_irq.h"
#include "drivers/lhal/include/bflb_pwm_v2.h"
#include "drivers/lhal/include/bflb_rtc.h"
#include "drivers/lhal/include/bflb_gpio.h"
#include "drivers/lhal/include/bflb_cks.h"
#include "drivers/lhal/include/bflb_clock.h"
#include "drivers/lhal/include/bflb_common.h"
#include "drivers/lhal/include/bflb_sec_dsa.h"
#include "drivers/lhal/include/bflb_cam.h"
#include "drivers/lhal/include/bflb_dac.h"
#include "drivers/lhal/include/bflb_csi.h"
#include "drivers/lhal/include/bflb_ef_ctrl.h"
#include "drivers/lhal/include/bflb_dma.h"
#include "drivers/lhal/include/bflb_kys.h"
#include "drivers/lhal/include/bflb_uart.h"
#include "drivers/lhal/include/bflb_flash.h"
#include "drivers/lhal/include/bflb_pwm_v1.h"
#include "drivers/lhal/include/bflb_platform_dma.h"
#include "drivers/lhal/include/bflb_list.h"
#include "drivers/lhal/include/bflb_timer.h"
#include "drivers/lhal/include/bflb_i2s.h"
#include "drivers/lhal/include/bflb_sec_pka.h"
#include "drivers/lhal/include/bflb_sec_aes.h"
#include "drivers/lhal/include/bflb_irq.h"
#include "drivers/lhal/include/bflb_spi_psram.h"
#include "drivers/lhal/include/bflb_mtimer.h"
#include "drivers/lhal/include/bflb_emac.h"
#include "drivers/lhal/include/bflb_adc.h"
#include "drivers/lhal/include/bflb_i2c.h"
#include "drivers/lhal/include/bflb_sdio2.h"
#include "drivers/lhal/include/bflb_efuse.h"
#include "drivers/lhal/include/bflb_ir.h"
#include "drivers/lhal/include/bflb_l1c.h"
#include "drivers/lhal/include/bflb_wdg.h"
#include "drivers/lhal/include/bflb_sec_trng.h"
#include "drivers/lhal/include/bflb_sec_ecdsa.h"

#include "drivers/lhal/src/flash/bflb_sf_cfg.h"
#include "drivers/lhal/src/flash/bflb_sf_ctrl.h"
#include "drivers/lhal/src/flash/bflb_sflash.h"
#include "drivers/lhal/src/flash/bflb_xip_sflash.h"

#include "components/libc/nuttx/nuttx_limits.h"
#include "components/libc/nuttx/config.h"
#include "components/libc/nuttx/compiler.h"
#include "components/libc/sys/types.h"
// #include "components/libc/newlib/"
#include "components/mm/mem.h"
#include "components/mm/tlsf/tlsf.h"
#include "components/utils/bflb_block_pool/bflb_block_pool.h"
#include "components/utils/bflb_ringbuffer/bflb_ringbuffer.h"
#include "components/utils/bflb_timestamp/bflb_timestamp.h"
#include "components/utils/getopt/utils_getopt.h"
// #include "components/utils/log/bflb_dbg.h"
#include "components/utils/ring_buffer/ring_buffer.h"

#include "components/os/freertos/include/FreeRTOS.h"
#include "components/os/freertos/include/task.h"

#ifdef __cplusplus
}
#endif

#endif // _BOUFFALO_SDK_H_