#!/usr/bin/env python3
"""Copy BL616CL firmware side-car artifacts into an Arduino build directory.

Usage: copy_image_artifacts.py SDK_PATH BUILD_PATH PROJECT_NAME

boot2 is read from the chip-level SDK (tools/sdk/{chip}/boot2/).
partition.bin and efusedata*.bin are generated by bflb_fw_post_proc alongside
the imgfile in BUILD_PATH and just need renaming to include the project name.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path


def main() -> int:
    if len(sys.argv) != 4:
        print(
            f"usage: {Path(sys.argv[0]).name} SDK_PATH BUILD_PATH PROJECT_NAME",
            file=sys.stderr,
        )
        return 2

    sdk_path = Path(sys.argv[1]).resolve()
    build_path = Path(sys.argv[2]).resolve()
    project_name = sys.argv[3]

    # Find the boot2 binary in the chip-level SDK directory.
    boot2_dir = sdk_path / "boot2"
    boot2_bins = sorted(boot2_dir.glob("boot2*.bin"))
    if not boot2_bins:
        print(f"no boot2 binary found in {boot2_dir}", file=sys.stderr)
        return 1
    boot2_source = boot2_bins[0]

    # bflb_fw_post_proc writes these alongside the imgfile in BUILD_PATH.
    generated = {
        "partition.bin": f"{project_name}.partition.bin",
        "efusedata.bin": f"{project_name}.efusedata.bin",
        "efusedata_mask.bin": f"{project_name}.efusedata_mask.bin",
        "efusedata_raw.bin": f"{project_name}.efusedata_raw.bin",
    }

    # Copy boot2.
    shutil.copy2(boot2_source, build_path / f"{project_name}.boot2.bin")

    # Rename generated side-car files.
    for source_name, dest_name in generated.items():
        source = build_path / source_name
        if not source.is_file():
            print(f"missing generated artifact: {source}", file=sys.stderr)
            return 1
        shutil.copy2(source, build_path / dest_name)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
